loaded=true
originalCategoryIconBase=org/netbeans/modules/autoupdate/services/resources/icon-standard.png
originalCategoryName=STANDARD
originalDisplayName=NetBeans Distribution
originalEnabled=true
originalUrl=http://updates.netbeans.org/netbeans/updates/8.2/uc/final/distribution/catalog.xml.gz?unique=NBJDK_EXTIDE_JAVA_JDK04655fcc6-1253-4ff0-acad-ddb41c85a620_b5c2c043-47fd-4955-92f9-8888d8152e5f
