wallpaper {
    monitor = HDMI-A-1
    path = /mnt/ISLAND/Files/Pictures/Wallpaper/TheWindGroup1.jpg
    fit_mode = cover
}

wallpaper {
    monitor = eDP-1
    path = /mnt/ISLAND/Files/Pictures/Wallpaper/TheWindGroup1.jpg
    fit_mode = cover
}

# Fallback para sa external displays
wallpaper {
    monitor = 
    path = /mnt/ISLAND/Files/Pictures/Wallpaper/TheWindGroup1.jpg
    fit_mode = cover
}

splash = false
ipc = true
